---
stages:
  - test
  - deploy
  - check

variables:
  target_folder: /opt/r8s
  scenario: k8s-nosdn-nofeature-noha

.syntax_checking: &syntax_docker
  stage: test
  tags:
    - shared
    - docker
    - innovation

yaml_checking:
  image: dockerproxy-iva.si.francetelecom.fr/sdesbure/yamllint:latest
  script:
    - yamllint .gitlab-ci.yml
    - yamllint *.y?ml
    - yamllint vars/*.y?ml
    - yamllint roles/*/tasks/*.y?ml
  <<: *syntax_docker

ansible_linting:
  image: dockerproxy-iva.si.francetelecom.fr/sdesbure/ansible-lint:latest
  script:
    - ansible-lint -x ANSIBLE0010,ANSIBLE0013 opnfv-*.yaml
  <<: *syntax_docker

# Deploy
.deploy_pod: &deploy_pod
  stage: deploy
  tags:
    - sina
    - shell
  only:
    - master
  script:
    - ssh ${pod}.opnfv.fr "sudo mkdir -p /opt/r8s ;
                           sudo chown -R ubuntu.ubuntu /opt/r8s"
    - cd vars
    - "git archive \
       --remote=git@gitlab.forge.orange-labs.fr:opnfv/TerraHouat.git \
       HEAD:config \
       ${pod}-k8s.yaml \
       | tar -x"
    - ln -s ${pod}-k8s.yaml pdf.yaml
    - cd ..
    - "rsync --cvs-exclude -e ssh -avz  \
      --delete-after . \
      ${pod}.opnfv.fr:${target_folder}"
    - ssh ${pod}.opnfv.fr "cd /opt/r8s; sudo ./run.sh"

deploy_pod1:
  variables:
    pod: pod1
  environment:
    name: pod1
    url: https://10.1.0.9/
  when: manual
  <<: *deploy_pod

deploy_pod2:
  variables:
    pod: pod2
    scenario: os-nosdn-nofeature-noha
  environment:
    name: pod2
    url: https://10.2.0.9/
  when: manual
  <<: *deploy_pod

deploy_pod4:
  variables:
    pod: pod4
    scenario: os-nosdn-nofeature-ha
  environment:
    name: pod4
    url: https://10.4.0.9/
  when: manual
  <<: *deploy_pod
